/**
 * @file        main.cpp
 * @title       Nextino Plug-and-Play Blink Demo
 * @description This file demonstrates the core "Plug-and-Play" philosophy of the
 *              Nextino framework. Notice how clean and simple it is!
 *
 * @author      Giorgi Magradze
 * @date        2025-08-24
 * @version     0.2.0
 */

#include <Arduino.h>
#include <Nextino.h>

// This header is auto-generated by the Nextino build script (`bootstrap.py`).
// It contains the aggregated JSON configuration and the registerAllModuleTypes() function.
#include "generated_config.h"

void setup() {
    // Step 1: Initialize the Logger as the very first action.
    Logger::getInstance().begin(LogLevel::Debug);

    // Add a small delay for the Serial Monitor to connect, especially on fast boards.
    delay(2000);

    NEXTINO_LOGI("Main", "--- Nextino Blink Demo ---");

    // Step 2: Register all discovered module types with the ModuleFactory.
    // This function is defined in the auto-generated "generated_config.h".
    registerAllModuleTypes();

    // Step 3: Start the Nextino system.
    // The SystemManager will now automatically parse the configuration,
    // lock resources, create modules, and call their init() and start() methods.
    NextinoSystem().begin(projectConfigJson);

    NEXTINO_LOGI("Main", "System is running (or in a safe error state).");
}

void loop()
{
    // Just let the Nextino system do its thing.
    NextinoSystem().loop();
}